### ISSUE TITLE
error on CMAKE command

### ISSUE THREAD

**Issue by dexKing07** [Chrisz236/llm-rk3588#1]
Hey there,
i'm using a OrangePi 5 8Gb RAM with Debian 12 Wormwhole and for some reason when i try to execute this command:

_cmake .. && cmake --build . --parallel $(nproc) && cd .._

I get this error:

```
orangepi@orangepi5:/app/ai/mlc-llm/build$ cmake .. && cmake --build . --parallel $(nproc) && cd ..
-- Hide private symbols
-- TVM_HOME: 3rdparty/tvm
-- Hide private symbols...
-- Forbidding undefined symbols in shared library, using -Wl,--no-undefined on platform Linux
-- Didn't find the path to CCACHE, disabling ccache
-- VTA build with VTA_HW_PATH=/app/ai/mlc-llm/3rdparty/tvm/3rdparty/vta-hw
-- Build VTA runtime with target: sim
-- Enabled runtime search for OpenCL library location
-- Couldn't build OpenCL-Gtests
-- Build with contrib.random
-- Build with contrib.sort
-- Build with contrib.hybriddump
-- Git found: /usr/bin/git
-- Found TVM_GIT_COMMIT_HASH=3001b20b0dd114cad23fccb25cbb055ce80a224e
-- Found TVM_GIT_COMMIT_TIME=2023-11-01 10:48:36 -0400
-- Building with TVM Map...
-- Build with thread support...
-- system-nameLinux
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE)
-- VERSION: 0.2.00
-- Found atomic: /usr/lib/aarch64-linux-gnu/libatomic.so.1
CMake Error at 3rdparty/tokenizers-cpp/CMakeLists.txt:131 (add_library):
  add_library INTERFACE library requires no source arguments.


CMake Error at 3rdparty/tokenizers-cpp/CMakeLists.txt:132 (target_link_libraries):
  Cannot specify link libraries for target "tokenizers_c" which is not built
  by this project.


-- Configuring incomplete, errors occurred!
See also "/app/ai/mlc-llm/build/CMakeFiles/CMakeOutput.log".
See also "/app/ai/mlc-llm/build/CMakeFiles/CMakeError.log".
```

I followed all the previous instructions without problems.
What could my problem be?
Thanks for your support.

**Comment by Chrisz236** [comment]
Seems error comes from “Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE)”. Try google search and install missing package then retry. Maybe because your system is too new or just different ditro have different libs pre installed.

**Comment by dexKing07** [comment]
Hi, thanks for your reply.
I have installed doxygen, but the problem is still there.
Any other idea ?
Can you share your output of this command, so i can compare it ?
Thanks again for your support.

**Comment by dexKing07** [comment]
Hi @Chrisz236,
sorry for the long time.
I wanted to tell you that in the end I solved the problem by buying an OPi5 Plus, and with Debian 12 Wormhole everything installed easily.
I can't tell you now if it's linked to a HW problem or the installed system, but the installation seems to be not compatible with the OPi5.
Thanks for the support.

**Comment by Chrisz236** [comment]
Ah, good to hear that. Have fun with your new OPi5 Plus :)
